### PR TITLE
NIFI-1819 MINIFI-31 Providing initial integration of MiNiFi site resources.

### PR DESCRIPTION
**Pull request by apiri**
NIFI-1819
MINIFI-31
Providing an initial incorporation of MiNiFi site content within the nifi site.  Performed some refactoring to make use of the assembly assets functionality for relative links to asset resources.

### CODE REVIEW

**Comment by JPercivall** [comment]
Do we want to do the two tone on "minifi" on the home page? Goes back to the discussion regarding the logo. Ideally it would convey "mini nifi" but I'm not sure the best way to do that.

Couple comments when clicking links from the MiNiFi index:
- "Contributor guide" goes to the NiFi contributor guide while a lot of the content is useful, almost all the commands are for NiFi
- "mailing lists" attempts to go to "dist/minifi/mailing_lists.html", which is not found
- "people" attempts to go to "dist/minifi/people.html", which is not found
- "developer guide" switches to "dist/developer-guide.html", the header is visible but the content cannot be found

**Comment by JPercivall** [comment]
@moranr how do you think the letters in "minifi" should be shaded?

**Comment by apiri** [comment]
The two tone is how NiFi was done, so I rolled a similar approach here.  No strong convictions either way.

Not sure we have anything substantive enough on this side to justify its own contributor guide.  

Adjusted the relative paths for people and mailing lists as these are the same and removed the developer guide link as one does not exist.

**Comment by JPercivall** [comment]
+1

All the links work and information is appropriate. If we want to revisit the coloring of minifi we can do so but the purpose of this PR is to get the site established.

**Pull request closed without merging**
